### PR TITLE
Adding missing markup changes, mostly around formatting

### PR DESCRIPTION
**Pull request by liam-philiben**
Added some additional markup edits. Most of the edits are around formatting (adding italics where necessary, putting things in block quotes for easier readability). I did add a link to the author's MoMA page, in case people wanted to know more about him.

Doing this as a step in the "Not Afraid to Commit" quest, thanks for checking it out!

### CODE REVIEW

**Review by jsundra — CHANGES_REQUESTED** [review]
This PR looks pretty solid as far as the changes go -- but one thing that's always important is a contextual PR title & description.

So for "merging edits to the doc from the Edit branch to main", while that's true, the title should be something more specific to the work being done, like "Add missing markup" or something similar.

The description often for a PR this small is just echoing the title, but a vary coarse "Added X, Y, Z to W page."

The reason for both of these is to provide reviewers with as much context as possible. The larger a codebase and/or team, the harder it is for everyone to keep track of the things they aren't directly working on.

**Comment by liam-philiben** [comment]
appreciate the feedback james! changed the title of the PR + the initial comment (not sure where to actually change the description of a PR, if that's not what you meant 😅)

**Comment by jsundra** [comment]
Ah yep! Description and the first comment are one in the same :)

**Review by jsundra — APPROVED** [review]
👍

**Review by gdamron — APPROVED** [review]
beautiful 🙂

**Pull request merged**
